server:
  port: 8087
spring:
  application:
    name: proyecto-java
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    database: mysql
    show-sql: true  
    hibernate:
      ddl-auto: update